spring.application.name=demo

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1

spring.datasource.username=system

spring.datasource.password=Oracle123!

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=validate

jwt.secret = E_valid_2026E_valid_2026E_valid_2026E_valid_2026E_valid_2026E_valid_2026E_valid_2026E_valid_2026E_valid_2026E_valid_2026E_valid_2026E_valid_2026
jwt.expiration.ms=3600000

